@url = http://localhost:5000/customers-service
@customerId = 00000000-0000-0000-0000-000000000001

###
GET {{url}}

###
GET {{url}}/customers/{{customerId}}

###
POST {{url}}/customers
Content-Type: application/json

{
  "email": "user1@inflow.io"
}

###
PUT {{url}}/customers/complete
Content-Type: application/json

{
  "name": "user1",
  "fullName": "John Doe",
  "address": "Test street 123",
  "nationality": "PL",
  "identityType": "id_card",
  "identitySeries": "ABC1234567"
}

###
PUT {{url}}/customers/{{customerId}}/verify
Content-Type: application/json

{
}

###
PUT {{url}}/customers/{{customerId}}/lock
Content-Type: application/json

{
}

###
PUT {{url}}/customers/{{customerId}}/unlock
Content-Type: application/json

{
}